In [1]:
import numpy as np

In [5]:
data = np.random.randn(2,3)
data

array([[-1.48867032, -0.72334405, -2.40537949],
       [-0.84836826, -0.71062561,  0.12016445]])

In [7]:
data*10

array([[-14.88670318,  -7.23344055, -24.05379492],
       [ -8.48368255,  -7.10625606,   1.20164447]])

In [8]:
data.shape

(2, 3)

In [9]:
data.dtype

dtype('float64')

# Creating ndarrays

In [14]:
data1=[1,2,6.5,8]
data1

[1, 2, 6.5, 8]

In [12]:
arr1 = np.array(data1)

In [13]:
arr1

array([1. , 2. , 6.5, 8. ])

In [16]:
data2 = [[1,2,3,4],[9,8,7,6]]
data2

[[1, 2, 3, 4], [9, 8, 7, 6]]

In [17]:
arr2 = np.array(data2)

In [18]:
arr2

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [19]:
arr2.ndim

2

In [20]:
arr2.shape

(2, 4)

In [21]:
arr2.dtype

dtype('int32')

In [22]:
arr1.dtype

dtype('float64')

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.empty((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Data Types for ndarrays

In [33]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [34]:
arr1.dtype

dtype('float64')

In [35]:
arr1 = arr1.astype(np.int64)

In [36]:
arr1.dtype

dtype('int64')

In [37]:
arr2 = np.array([1.5,3.4,4.9])

In [40]:
arr2 = arr2.astype(np.int64)
arr2

array([1, 3, 4], dtype=int64)

In [42]:
arr2 = arr2.astype(np.string_)
arr2

array([b'1', b'3', b'4'], dtype='|S21')

# Arithmetic with NumPy Arrays

In [44]:
arr = np.array(([1,2,3],[4,5,6]))

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [47]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [48]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [49]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [50]:
arr > 3

array([[False, False, False],
       [ True,  True,  True]])

# Basic Indexing and Slicing

In [52]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr[:3] = 0
arr

array([0, 0, 0, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [57]:
arr_slice[1] = 1122

In [58]:
arr_slice

array([   5, 1122,    7])

In [59]:
arr

array([   0,    0,    0,    3,    4,    5, 1122,    7,    8,    9])

In [64]:
arr2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2d[2]

array([7, 8, 9])

In [66]:
arr2d[0][0]

1

In [67]:
arr2d[0,0]

1

In [68]:
arr3d = np.array(([[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                   [10,11,12]]))

In [70]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [71]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr3d[0] = 77
arr3d

array([[[77, 77, 77],
        [77, 77, 77]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[1,0]

array([7, 8, 9])

In [83]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [85]:
arr2d[1,:2]

array([4, 5])

In [86]:
arr2d[:2,2]

array([3, 6])

In [87]:
arr2d[:,:1]

array([[1],
       [4],
       [7]])

In [90]:
arr2d[:2,1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [97]:
arr2d[1,:2].ndim

1

In [98]:
arr2d[1:2,:2].ndim

2

# Boolean Indexing

In [103]:
names = np.array(['Bob','Joe','Bob','Will','Bob','Bob','Will'])
names

array(['Bob', 'Joe', 'Bob', 'Will', 'Bob', 'Bob', 'Will'], dtype='<U4')

In [102]:
data = np.random.randn(7,4)
data

array([[-0.49141723,  0.07292187, -1.88650641,  1.78781118],
       [-0.21372375, -0.0982909 ,  1.03329377, -1.8999279 ],
       [-0.08008881, -0.6634564 , -1.55045873, -0.77985347],
       [ 0.51725361,  0.03266252, -0.82438261, -1.4984477 ],
       [-0.25641901, -1.26906637,  0.89848774, -0.63937124],
       [ 0.40064691,  0.95185999,  0.46753019, -1.24530805],
       [-0.68564458, -1.48760471,  0.99894859,  0.54465742]])

In [104]:
names == 'Bob'

array([ True, False,  True, False,  True,  True, False])

In [105]:
data[names == 'Bob'] 

array([[-0.49141723,  0.07292187, -1.88650641,  1.78781118],
       [-0.08008881, -0.6634564 , -1.55045873, -0.77985347],
       [-0.25641901, -1.26906637,  0.89848774, -0.63937124],
       [ 0.40064691,  0.95185999,  0.46753019, -1.24530805]])

In [106]:
data[names == 'Bob',2:]

array([[-1.88650641,  1.78781118],
       [-1.55045873, -0.77985347],
       [ 0.89848774, -0.63937124],
       [ 0.46753019, -1.24530805]])

In [107]:
data[~(names == 'Bob')]

array([[-0.21372375, -0.0982909 ,  1.03329377, -1.8999279 ],
       [ 0.51725361,  0.03266252, -0.82438261, -1.4984477 ],
       [-0.68564458, -1.48760471,  0.99894859,  0.54465742]])

In [108]:
cond = names == 'Bob'
data[~cond]

array([[-0.21372375, -0.0982909 ,  1.03329377, -1.8999279 ],
       [ 0.51725361,  0.03266252, -0.82438261, -1.4984477 ],
       [-0.68564458, -1.48760471,  0.99894859,  0.54465742]])

In [110]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True,  True,  True])

In [118]:
data[mask]

array([[-0.49141723,  0.07292187, -1.88650641,  1.78781118],
       [-0.08008881, -0.6634564 , -1.55045873, -0.77985347],
       [ 0.51725361,  0.03266252, -0.82438261, -1.4984477 ],
       [-0.25641901, -1.26906637,  0.89848774, -0.63937124],
       [ 0.40064691,  0.95185999,  0.46753019, -1.24530805],
       [-0.68564458, -1.48760471,  0.99894859,  0.54465742]])

In [120]:
data[data<0] = 0
data

array([[0.        , 0.07292187, 0.        , 1.78781118],
       [0.        , 0.        , 1.03329377, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.51725361, 0.03266252, 0.        , 0.        ],
       [0.        , 0.        , 0.89848774, 0.        ],
       [0.40064691, 0.95185999, 0.46753019, 0.        ],
       [0.        , 0.        , 0.99894859, 0.54465742]])

# Fancy Indexing

In [126]:
arr = np.empty((8,4))

In [127]:
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [128]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [129]:
arr[[-1,-2]]

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.]])

In [131]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [133]:
arr[[5,4,3],[2,1,0]]

array([22, 17, 12])

In [134]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# TRANSPOSING ARRAYS AND SWAPPING AXES